/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeriesDetailRouteImport } from './routes/series-detail'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MovieRouteImport } from './routes/movie'
import { Route as LiveRouteImport } from './routes/live'
import { Route as KidsDetailRouteImport } from './routes/kids-detail'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as FindMeRouteImport } from './routes/find-me'
import { Route as EpgRouteImport } from './routes/epg'
import { Route as IndexRouteImport } from './routes/index'

const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesDetailRoute = SeriesDetailRouteImport.update({
  id: '/series-detail',
  path: '/series-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieRoute = MovieRouteImport.update({
  id: '/movie',
  path: '/movie',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsDetailRoute = KidsDetailRouteImport.update({
  id: '/kids-detail',
  path: '/kids-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMeRoute = FindMeRouteImport.update({
  id: '/find-me',
  path: '/find-me',
  getParentRoute: () => rootRouteImport,
} as any)
const EpgRoute = EpgRouteImport.update({
  id: '/epg',
  path: '/epg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/find-me': typeof FindMeRoute
  '/kids': typeof KidsRoute
  '/kids-detail': typeof KidsDetailRoute
  '/live': typeof LiveRoute
  '/movie': typeof MovieRoute
  '/movies': typeof MoviesRoute
  '/player': typeof PlayerRoute
  '/profiles': typeof ProfilesRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/series-detail': typeof SeriesDetailRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/find-me': typeof FindMeRoute
  '/kids': typeof KidsRoute
  '/kids-detail': typeof KidsDetailRoute
  '/live': typeof LiveRoute
  '/movie': typeof MovieRoute
  '/movies': typeof MoviesRoute
  '/player': typeof PlayerRoute
  '/profiles': typeof ProfilesRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/series-detail': typeof SeriesDetailRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/find-me': typeof FindMeRoute
  '/kids': typeof KidsRoute
  '/kids-detail': typeof KidsDetailRoute
  '/live': typeof LiveRoute
  '/movie': typeof MovieRoute
  '/movies': typeof MoviesRoute
  '/player': typeof PlayerRoute
  '/profiles': typeof ProfilesRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/series-detail': typeof SeriesDetailRoute
  '/settings': typeof SettingsRoute
  '/sports': typeof SportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epg'
    | '/find-me'
    | '/kids'
    | '/kids-detail'
    | '/live'
    | '/movie'
    | '/movies'
    | '/player'
    | '/profiles'
    | '/search'
    | '/series'
    | '/series-detail'
    | '/settings'
    | '/sports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epg'
    | '/find-me'
    | '/kids'
    | '/kids-detail'
    | '/live'
    | '/movie'
    | '/movies'
    | '/player'
    | '/profiles'
    | '/search'
    | '/series'
    | '/series-detail'
    | '/settings'
    | '/sports'
  id:
    | '__root__'
    | '/'
    | '/epg'
    | '/find-me'
    | '/kids'
    | '/kids-detail'
    | '/live'
    | '/movie'
    | '/movies'
    | '/player'
    | '/profiles'
    | '/search'
    | '/series'
    | '/series-detail'
    | '/settings'
    | '/sports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpgRoute: typeof EpgRoute
  FindMeRoute: typeof FindMeRoute
  KidsRoute: typeof KidsRoute
  KidsDetailRoute: typeof KidsDetailRoute
  LiveRoute: typeof LiveRoute
  MovieRoute: typeof MovieRoute
  MoviesRoute: typeof MoviesRoute
  PlayerRoute: typeof PlayerRoute
  ProfilesRoute: typeof ProfilesRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  SeriesDetailRoute: typeof SeriesDetailRoute
  SettingsRoute: typeof SettingsRoute
  SportsRoute: typeof SportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series-detail': {
      id: '/series-detail'
      path: '/series-detail'
      fullPath: '/series-detail'
      preLoaderRoute: typeof SeriesDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie': {
      id: '/movie'
      path: '/movie'
      fullPath: '/movie'
      preLoaderRoute: typeof MovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-detail': {
      id: '/kids-detail'
      path: '/kids-detail'
      fullPath: '/kids-detail'
      preLoaderRoute: typeof KidsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-me': {
      id: '/find-me'
      path: '/find-me'
      fullPath: '/find-me'
      preLoaderRoute: typeof FindMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epg': {
      id: '/epg'
      path: '/epg'
      fullPath: '/epg'
      preLoaderRoute: typeof EpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpgRoute: EpgRoute,
  FindMeRoute: FindMeRoute,
  KidsRoute: KidsRoute,
  KidsDetailRoute: KidsDetailRoute,
  LiveRoute: LiveRoute,
  MovieRoute: MovieRoute,
  MoviesRoute: MoviesRoute,
  PlayerRoute: PlayerRoute,
  ProfilesRoute: ProfilesRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  SeriesDetailRoute: SeriesDetailRoute,
  SettingsRoute: SettingsRoute,
  SportsRoute: SportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
